spring:
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
   resources: 
      static-locations: classpath:/static
   datasource:
      url: jdbc:mysql://localhost:3306/springboot_ssm?useUnicode=true&characterEncoding=UTF8
      username: xpzheng
      password: 123456
   devtools:
      restart:
         enabled: true
         exclude: test/**
      
mybatis:
   config-location: classpath:mybatis/mybatis-config.xml
   mapper-locations: classpath:mybatis/mapper/*.xml
   
server:
   port: 80