DROP DATABASE IF EXISTS springboot_ssm;

CREATE DATABASE springboot_ssm DEFAULT CHARACTER SET UTF8;
USE springboot_ssm;

CREATE TABLE t_user(
	id BIGINT AUTO_INCREMENT,
	account VARCHAR(20) NOT NULL,
	password VARCHAR(20) NOT NULL,
	name VARCHAR(20) NOT NULL DEFAULT '',
	age INT DEFAULT 1,
	PRIMARY KEY(id)
);